apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-service
  labels:
    app: payment-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payment-service
  template:
    metadata:
      labels:
        app: payment-service
    spec:
      containers:
        - name: payment-service
          image: healthlink-payment-service:local
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 4006
          envFrom:
            - configMapRef:
                name: payment-service-config
            - secretRef:
                name: payment-service-secret
          readinessProbe:
            httpGet:
              path: /health
              port: 4006
            initialDelaySeconds: 10
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /health
              port: 4006
            initialDelaySeconds: 20
            periodSeconds: 20
