apiVersion: v1
kind: Secret
metadata:
  name: ai-service-secret
type: Opaque
stringData:
  MONGO_URI: "changeme-mongodb-uri"
  JWT_SECRET: "changeme-jwt-secret"
  COHERE_API_KEY: "changeme-cohere-api-key"