apiVersion: v1
kind: Secret
metadata:
  name: ai-service-secret
type: Opaque
stringData:
  MONGO_URI: "mongodb+srv://healthlink:123456Aa@cluster0.5ccblix.mongodb.net/ai-db?appName=Cluster0"
  JWT_SECRET: "access_secret_123456789_secure_key_service"
  COHERE_API_KEY: "cohereapikey"
