apiVersion: v1
kind: ConfigMap
metadata:
  name: appointment-service-config
data:
  CORS_ORIGIN: "http://localhost:3000"
  REQUEST_TIMEOUT_MS: "5000"
  DOCTOR_SERVICE_URL: "http://doctor-service"
  TELEMEDICINE_SERVICE_URL: "http://telemedicine-service:4004"
  PAYMENT_SERVICE_URL: "http://payment-service:4006"
  NOTIFICATION_SERVICE_URL: "http://notification-service:3005"
