apiVersion: v1
kind: Secret
metadata:
  name: appointment-service-secret
type: Opaque
stringData:
  MONGODB_URI: "mongodb+srv://healthlink:123456Aa@cluster0.5ccblix.mongodb.net/appointment-db?appName=Cluster0"
  JWT_ACCESS_SECRET: "access_secret_123456789_secure_key_service"
