apiVersion: v1
kind: ConfigMap
metadata:
  name: auth-service-config
data:
  ACCESS_TOKEN_EXPIRES_IN: "15m"
  REFRESH_TOKEN_EXPIRES_IN: "7d"
  BCRYPT_SALT_ROUNDS: "12"
  CORS_ORIGIN: "http://localhost:3000"
  DOCTOR_SERVICE_URL: "http://doctor-service:4002"
  PATIENT_SERVICE_URL: "http://patient-service:4003"
  INTERNAL_SERVICE_API_KEY: "healthlink-internal-key"
  REQUEST_TIMEOUT_MS: "5000"
