apiVersion: v1
kind: Secret
metadata:
  name: doctor-service-secret
type: Opaque
stringData:
  MONGODB_URI: "mongodb://mongo:27017/doctor-db"
  JWT_ACCESS_SECRET: "access_secret_123456789_secure_key_service"
  JWT_SECRET: "your_super_secret_jwt_key_here"
