apiVersion: v1
kind: ConfigMap
metadata:
  name: notification-service-config
data:
  PORT: "4007"
  HOST: "0.0.0.0"
  CORS_ORIGIN: "http://localhost:3000"
  AUTH_REQUIRED: "false"
  ALLOWED_SERVICE_CALLERS: "appointment-service,doctor-service,payment-service,telemedicine-service"
