apiVersion: v1
kind: Secret
metadata:
  name: payment-service-secret
type: Opaque
stringData:
  MONGO_URI: "mongodb+srv://healthlink:123456Aa@cluster0.5ccblix.mongodb.net/payment-db?appName=Cluster0"
  JWT_SECRET: "access_secret_123456789_secure_key_service"
  STRIPE_SECRET_KEY: "REPLACE_WITH_STRIPE_SECRET_KEY"
  STRIPE_WEBHOOK_SECRET: "REPLACE_WITH_STRIPE_WEBHOOK_SECRET"
