apiVersion: v1
kind: ConfigMap
metadata:
  name: payment-service-config
data:
  PORT: "4006"
  CORS_ORIGIN: "http://localhost:3000"
  UPLOAD_PATH: "uploads"
  APPOINTMENT_SERVICE_URL: "http://appointment-service"
  DOCTOR_SERVICE_URL: "http://doctor-service"
  REQUEST_TIMEOUT_MS: "5000"
  DEFAULT_CONSULTATION_FEE: "1000"
